# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SSIS_Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1315, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #18191a")
        self.centralwidget.setObjectName("centralwidget")
        self.SideFrame = QtWidgets.QFrame(self.centralwidget)
        self.SideFrame.setGeometry(QtCore.QRect(0, 0, 201, 561))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.SideFrame.setFont(font)
        self.SideFrame.setStyleSheet("background-color: #242526")
        self.SideFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SideFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SideFrame.setObjectName("SideFrame")
        self.SideStackWidget = QtWidgets.QStackedWidget(self.SideFrame)
        self.SideStackWidget.setGeometry(QtCore.QRect(0, 80, 201, 481))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SideStackWidget.setFont(font)
        self.SideStackWidget.setObjectName("SideStackWidget")
        self.Default = QtWidgets.QWidget()
        self.Default.setObjectName("Default")
        self.frame_8 = QtWidgets.QFrame(self.Default)
        self.frame_8.setGeometry(QtCore.QRect(20, 30, 161, 41))
        self.frame_8.setStyleSheet("QFrame {\n"
"    border: 2px solid #00C9FF;\n"
"}\n"
"\n"
"QFrame > * {\n"
"    border: none;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    color: #00C9FF;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.SideStackWidget.addWidget(self.Default)
        self.AddStudentPage = QtWidgets.QWidget()
        self.AddStudentPage.setObjectName("AddStudentPage")
        self.Name = QtWidgets.QLineEdit(self.AddStudentPage)
        self.Name.setGeometry(QtCore.QRect(10, 110, 181, 20))
        self.Name.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #00C9FF;\n"
"    color: #00C9FF;  /* Text color of QLineEdit */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #00C9FF;  /* Text color of placeholder */\n"
"    text-align: center;\n"
"}")
        self.Name.setObjectName("Name")
        self.StudentID = QtWidgets.QLineEdit(self.AddStudentPage)
        self.StudentID.setGeometry(QtCore.QRect(100, 190, 95, 20))
        self.StudentID.setStyleSheet("QLineEdit{\n"
"border: 1px solid #00C9FF;\n"
"color: #00C9FF;\n"
"text-align: center;\n"
"}")
        self.StudentID.setObjectName("StudentID")
        self.Gender = QtWidgets.QComboBox(self.AddStudentPage)
        self.Gender.setGeometry(QtCore.QRect(120, 260, 60, 22))
        self.Gender.setStyleSheet("QComboBox {\n"
"    border: 1px solid #00C9FF;\n"
"}")
        self.Gender.setObjectName("Gender")
        self.YearLevel = QtWidgets.QLineEdit(self.AddStudentPage)
        self.YearLevel.setGeometry(QtCore.QRect(10, 150, 141, 20))
        self.YearLevel.setStyleSheet("QLineEdit{\n"
"border: 1px solid #00C9FF;\n"
"color: #00C9FF;\n"
"text-align: center;\n"
"}")
        self.YearLevel.setObjectName("YearLevel")
        self.CouseCode = QtWidgets.QComboBox(self.AddStudentPage)
        self.CouseCode.setGeometry(QtCore.QRect(10, 230, 101, 22))
        self.CouseCode.setStyleSheet("QComboBox {\n"
"    border: 1px solid #00C9FF;\n"
"}")
        self.CouseCode.setPlaceholderText("")
        self.CouseCode.setObjectName("CouseCode")
        self.frame = QtWidgets.QFrame(self.AddStudentPage)
        self.frame.setGeometry(QtCore.QRect(20, 30, 161, 41))
        self.frame.setStyleSheet("QFrame {\n"
"    border: 2px solid #00C9FF;\n"
"}\n"
"\n"
"QFrame > * {\n"
"    border: none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #00C9FF;\n"
"}")
        self.label.setObjectName("label")
        self.SaveStudent = QtWidgets.QPushButton(self.AddStudentPage)
        self.SaveStudent.setGeometry(QtCore.QRect(40, 320, 101, 31))
        self.SaveStudent.setStyleSheet("QPushButton {\n"
"    border: 2px solid #00C9FF;\n"
"    color: #00C9FF;  /* Text color of QPushButton */\n"
"    text-align: center;  /* Center-align text in QPushButton */\n"
"}")
        self.SaveStudent.setObjectName("SaveStudent")
        self.SideStackWidget.addWidget(self.AddStudentPage)
        self.AddCoursePage = QtWidgets.QWidget()
        self.AddCoursePage.setObjectName("AddCoursePage")
        self.frame_2 = QtWidgets.QFrame(self.AddCoursePage)
        self.frame_2.setGeometry(QtCore.QRect(20, 30, 161, 41))
        self.frame_2.setStyleSheet("QFrame {\n"
"    border: 2px solid #00C9FF;\n"
"}\n"
"\n"
"QFrame > * {\n"
"    border: none;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #00C9FF;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.CourseCodeAdd = QtWidgets.QLineEdit(self.AddCoursePage)
        self.CourseCodeAdd.setGeometry(QtCore.QRect(40, 230, 113, 20))
        self.CourseCodeAdd.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #00C9FF;\n"
"    color: #00C9FF;  /* Text color of QLineEdit */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #00C9FF;  /* Text color of placeholder */\n"
"    text-align: center;\n"
"}")
        self.CourseCodeAdd.setObjectName("CourseCodeAdd")
        self.SaveCourse = QtWidgets.QPushButton(self.AddCoursePage)
        self.SaveCourse.setGeometry(QtCore.QRect(40, 320, 101, 31))
        self.SaveCourse.setStyleSheet("QPushButton {\n"
"    border: 2px solid #00C9FF;\n"
"    color: #00C9FF;  /* Text color of QPushButton */\n"
"    text-align: center;  /* Center-align text in QPushButton */\n"
"}")
        self.SaveCourse.setObjectName("SaveCourse")
        self.CourseNameAdd = QtWidgets.QTextEdit(self.AddCoursePage)
        self.CourseNameAdd.setGeometry(QtCore.QRect(10, 120, 171, 64))
        self.CourseNameAdd.setStyleSheet("QTextEdit {\n"
"    border: 1px solid #00C9FF;\n"
"    color: #00C9FF;  /* Text color of QTextEdit */\n"
"    background-color: transparent;  /* Make the background transparent */\n"
"    padding: 5px;  /* Add padding for better visibility */\n"
"}\n"
"\n"
"QTextEdit::placeholder {\n"
"    color: #00C9FF;  /* Text color of placeholder */\n"
"    background-color: transparent;  /* Make the background transparent */\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width: 10px;  /* Customize vertical scrollbar width */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #00C9FF;  /* Customize scrollbar handle color */\n"
"    border-radius: 5px;  /* Add border radius to scrollbar handle */\n"
"}")
        self.CourseNameAdd.setObjectName("CourseNameAdd")
        self.SideStackWidget.addWidget(self.AddCoursePage)
        self.EditStudentPage = QtWidgets.QWidget()
        self.EditStudentPage.setObjectName("EditStudentPage")
        self.NameEdit = QtWidgets.QLineEdit(self.EditStudentPage)
        self.NameEdit.setGeometry(QtCore.QRect(10, 90, 181, 20))
        self.NameEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #00C9FF;\n"
"    color: #00C9FF;  /* Text color of QLineEdit */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #00C9FF;  /* Text color of placeholder */\n"
"    text-align: center;\n"
"}")
        self.NameEdit.setObjectName("NameEdit")
        self.YearLevelEdit = QtWidgets.QLineEdit(self.EditStudentPage)
        self.YearLevelEdit.setGeometry(QtCore.QRect(10, 140, 141, 20))
        self.YearLevelEdit.setStyleSheet("QLineEdit{\n"
"border: 1px solid #00C9FF;\n"
"color: #00C9FF;\n"
"text-align: center;\n"
"}")
        self.YearLevelEdit.setObjectName("YearLevelEdit")
        self.StudentIDEdit = QtWidgets.QLineEdit(self.EditStudentPage)
        self.StudentIDEdit.setGeometry(QtCore.QRect(10, 200, 95, 20))
        self.StudentIDEdit.setStyleSheet("QLineEdit{\n"
"border: 1px solid #00C9FF;\n"
"color: #00C9FF;\n"
"text-align: center;\n"
"}")
        self.StudentIDEdit.setObjectName("StudentIDEdit")
        self.CouseCodeEdit = QtWidgets.QComboBox(self.EditStudentPage)
        self.CouseCodeEdit.setGeometry(QtCore.QRect(10, 250, 101, 22))
        self.CouseCodeEdit.setStyleSheet("QComboBox {\n"
"    border: 1px solid #00C9FF;\n"
"}")
        self.CouseCodeEdit.setPlaceholderText("")
        self.CouseCodeEdit.setObjectName("CouseCodeEdit")
        self.GenderEdit = QtWidgets.QComboBox(self.EditStudentPage)
        self.GenderEdit.setGeometry(QtCore.QRect(130, 250, 60, 22))
        self.GenderEdit.setStyleSheet("QComboBox {\n"
"    border: 1px solid #00C9FF;\n"
"}")
        self.GenderEdit.setObjectName("GenderEdit")
        self.SaveStudentEdit = QtWidgets.QPushButton(self.EditStudentPage)
        self.SaveStudentEdit.setGeometry(QtCore.QRect(40, 320, 101, 31))
        self.SaveStudentEdit.setStyleSheet("QPushButton {\n"
"    border: 2px solid #00C9FF;\n"
"    color: #00C9FF;  /* Text color of QPushButton */\n"
"    text-align: center;  /* Center-align text in QPushButton */\n"
"}")
        self.SaveStudentEdit.setObjectName("SaveStudentEdit")
        self.frame_3 = QtWidgets.QFrame(self.EditStudentPage)
        self.frame_3.setGeometry(QtCore.QRect(10, 30, 171, 41))
        self.frame_3.setStyleSheet("QFrame {\n"
"    border: 2px solid #00C9FF;\n"
"}\n"
"\n"
"QFrame > * {\n"
"    border: none;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: #00C9FF;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.SideStackWidget.addWidget(self.EditStudentPage)
        self.EditCoursePage = QtWidgets.QWidget()
        self.EditCoursePage.setObjectName("EditCoursePage")
        self.frame_4 = QtWidgets.QFrame(self.EditCoursePage)
        self.frame_4.setGeometry(QtCore.QRect(10, 30, 171, 41))
        self.frame_4.setStyleSheet("QFrame {\n"
"    border: 2px solid #00C9FF;\n"
"}\n"
"\n"
"QFrame > * {\n"
"    border: none;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: #00C9FF;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.CourseNameEdit = QtWidgets.QTextEdit(self.EditCoursePage)
        self.CourseNameEdit.setGeometry(QtCore.QRect(10, 130, 171, 64))
        self.CourseNameEdit.setStyleSheet("QTextEdit {\n"
"    border: 1px solid #00C9FF;\n"
"    color: #00C9FF;  /* Text color of QTextEdit */\n"
"    background-color: transparent;  /* Make the background transparent */\n"
"    padding: 5px;  /* Add padding for better visibility */\n"
"}\n"
"\n"
"QTextEdit::placeholder {\n"
"    color: #00C9FF;  /* Text color of placeholder */\n"
"    background-color: transparent;  /* Make the background transparent */\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width: 10px;  /* Customize vertical scrollbar width */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #00C9FF;  /* Customize scrollbar handle color */\n"
"    border-radius: 5px;  /* Add border radius to scrollbar handle */\n"
"}")
        self.CourseNameEdit.setObjectName("CourseNameEdit")
        self.CourseCodeCourseEdit = QtWidgets.QLineEdit(self.EditCoursePage)
        self.CourseCodeCourseEdit.setGeometry(QtCore.QRect(30, 240, 113, 20))
        self.CourseCodeCourseEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #00C9FF;\n"
"    color: #00C9FF;  /* Text color of QLineEdit */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #00C9FF;  /* Text color of placeholder */\n"
"    text-align: center;\n"
"}")
        self.CourseCodeCourseEdit.setObjectName("CourseCodeCourseEdit")
        self.SaveCourseEdit = QtWidgets.QPushButton(self.EditCoursePage)
        self.SaveCourseEdit.setGeometry(QtCore.QRect(40, 320, 101, 31))
        self.SaveCourseEdit.setStyleSheet("QPushButton {\n"
"    border: 2px solid #00C9FF;\n"
"    color: #00C9FF;  /* Text color of QPushButton */\n"
"    text-align: center;  /* Center-align text in QPushButton */\n"
"}")
        self.SaveCourseEdit.setObjectName("SaveCourseEdit")
        self.SideStackWidget.addWidget(self.EditCoursePage)
        self.DeletePage = QtWidgets.QWidget()
        self.DeletePage.setObjectName("DeletePage")
        self.frame_5 = QtWidgets.QFrame(self.DeletePage)
        self.frame_5.setGeometry(QtCore.QRect(10, 30, 171, 41))
        self.frame_5.setStyleSheet("QFrame {\n"
"    border: 2px solid #FF073A;\n"
"}\n"
"\n"
"QFrame > * {\n"
"    border: none;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    color: #FF073A;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.frame_6 = QtWidgets.QFrame(self.DeletePage)
        self.frame_6.setGeometry(QtCore.QRect(20, 200, 161, 171))
        self.frame_6.setStyleSheet("QFrame {\n"
"    border: 2px solid #FF073A;\n"
"}\n"
"\n"
"QFrame > * {\n"
"    border: none;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 151, 41))
        self.label_8.setStyleSheet("QLabel {\n"
"    color: #FFFF00;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(20, 80, 121, 20))
        self.label_9.setStyleSheet("QLabel {\n"
"    color: #FFFF00;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.frame_7 = QtWidgets.QFrame(self.DeletePage)
        self.frame_7.setGeometry(QtCore.QRect(25, 120, 151, 41))
        self.frame_7.setStyleSheet("QFrame {\n"
"    border: 2px solid #FF073A;\n"
"}\n"
"\n"
"QFrame > * {\n"
"    border: none;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    color: #FFFF00;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.SideStackWidget.addWidget(self.DeletePage)
        self.DefaultEditPage = QtWidgets.QWidget()
        self.DefaultEditPage.setObjectName("DefaultEditPage")
        self.frame_9 = QtWidgets.QFrame(self.DefaultEditPage)
        self.frame_9.setGeometry(QtCore.QRect(20, 30, 161, 41))
        self.frame_9.setStyleSheet("QFrame {\n"
"    border: 2px solid #00C9FF;\n"
"}\n"
"\n"
"QFrame > * {\n"
"    border: none;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    color: #00C9FF;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.frame_10 = QtWidgets.QFrame(self.DefaultEditPage)
        self.frame_10.setGeometry(QtCore.QRect(20, 120, 161, 171))
        self.frame_10.setStyleSheet("QFrame {\n"
"    border: 2px solid #00C9FF;\n"
"}\n"
"\n"
"QFrame > * {\n"
"    border: none;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        self.label_13.setGeometry(QtCore.QRect(10, 30, 151, 41))
        self.label_13.setStyleSheet("QLabel {\n"
"    color: #00C9FF;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_10)
        self.label_14.setGeometry(QtCore.QRect(20, 80, 121, 20))
        self.label_14.setStyleSheet("QLabel {\n"
"    color: #00C9FF;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.SideStackWidget.addWidget(self.DefaultEditPage)
        self.label_3 = QtWidgets.QLabel(self.SideFrame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 47, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icons/letter-s.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.SideFrame)
        self.label_4.setGeometry(QtCore.QRect(70, 15, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white\n"
"")
        self.label_4.setObjectName("label_4")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setGeometry(QtCore.QRect(200, 80, 1111, 481))
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.StudentTable = QtWidgets.QTableWidget(self.MainFrame)
        self.StudentTable.setGeometry(QtCore.QRect(0, 10, 601, 471))
        self.StudentTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: #00C9FF;\n"
"}")
        self.StudentTable.setObjectName("StudentTable")
        self.StudentTable.setColumnCount(5)
        self.StudentTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.StudentTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentTable.setHorizontalHeaderItem(4, item)
        self.CourseTable = QtWidgets.QTableWidget(self.MainFrame)
        self.CourseTable.setGeometry(QtCore.QRect(610, 10, 461, 471))
        self.CourseTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: #00C9FF;\n"
"}")
        self.CourseTable.setObjectName("CourseTable")
        self.CourseTable.setColumnCount(2)
        self.CourseTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setHorizontalHeaderItem(1, item)
        self.UpperFrame = QtWidgets.QFrame(self.centralwidget)
        self.UpperFrame.setGeometry(QtCore.QRect(199, 0, 1131, 81))
        self.UpperFrame.setToolTip("")
        self.UpperFrame.setStyleSheet("background-color: #3a3b3c")
        self.UpperFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UpperFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UpperFrame.setObjectName("UpperFrame")
        self.SearchStudent = QtWidgets.QLineEdit(self.UpperFrame)
        self.SearchStudent.setGeometry(QtCore.QRect(50, 50, 191, 20))
        self.SearchStudent.setStyleSheet("QLineEdit{\n"
"border: 2px solid #00C9FF;\n"
"color: #00C9FF;\n"
"text-align: center;\n"
"}")
        self.SearchStudent.setObjectName("SearchStudent")
        self.SearchCourse = QtWidgets.QLineEdit(self.UpperFrame)
        self.SearchCourse.setGeometry(QtCore.QRect(690, 50, 171, 21))
        self.SearchCourse.setStyleSheet("QLineEdit{\n"
"border: 2px solid #00C9FF;\n"
"color: #00C9FF;\n"
"text-align: center;\n"
"}")
        self.SearchCourse.setObjectName("SearchCourse")
        self.SearchStudentB = QtWidgets.QPushButton(self.UpperFrame)
        self.SearchStudentB.setGeometry(QtCore.QRect(10, 50, 31, 21))
        self.SearchStudentB.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchStudentB.setIcon(icon)
        self.SearchStudentB.setObjectName("SearchStudentB")
        self.EditButton = QtWidgets.QPushButton(self.UpperFrame)
        self.EditButton.setGeometry(QtCore.QRect(490, 50, 41, 23))
        self.EditButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EditButton.setIcon(icon1)
        self.EditButton.setObjectName("EditButton")
        self.DeleteButton = QtWidgets.QPushButton(self.UpperFrame)
        self.DeleteButton.setGeometry(QtCore.QRect(540, 50, 41, 23))
        self.DeleteButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DeleteButton.setIcon(icon2)
        self.DeleteButton.setObjectName("DeleteButton")
        self.ViewButton = QtWidgets.QPushButton(self.UpperFrame)
        self.ViewButton.setGeometry(QtCore.QRect(440, 50, 41, 23))
        self.ViewButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/eye-test.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ViewButton.setIcon(icon3)
        self.ViewButton.setObjectName("ViewButton")
        self.SearchCourseB = QtWidgets.QPushButton(self.UpperFrame)
        self.SearchCourseB.setGeometry(QtCore.QRect(650, 50, 31, 23))
        self.SearchCourseB.setText("")
        self.SearchCourseB.setIcon(icon)
        self.SearchCourseB.setObjectName("SearchCourseB")
        self.AddStudentB = QtWidgets.QPushButton(self.UpperFrame)
        self.AddStudentB.setGeometry(QtCore.QRect(260, 50, 41, 23))
        self.AddStudentB.setStyleSheet("")
        self.AddStudentB.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddStudentB.setIcon(icon4)
        self.AddStudentB.setObjectName("AddStudentB")
        self.AddCourseB = QtWidgets.QPushButton(self.UpperFrame)
        self.AddCourseB.setGeometry(QtCore.QRect(880, 50, 41, 23))
        self.AddCourseB.setText("")
        self.AddCourseB.setIcon(icon4)
        self.AddCourseB.setObjectName("AddCourseB")
        MainWindow.setCentralWidget(self.centralwidget)


        #self.Course.addItem("Not Enrolled")                                                             #Modified
        self.CourseTable.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)    #Modified
        self.CourseTable.horizontalHeader().setStretchLastSection(True)                                     #Modified 

        self.StudentTable.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)    #Modified
        self.StudentTable.horizontalHeader().setStretchLastSection(True)                                     #Modified 
        


        self.retranslateUi(MainWindow)
        self.SideStackWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", " VIEW MODE"))
        self.Name.setToolTip(_translate("MainWindow", "Student Name"))
        self.Name.setPlaceholderText(_translate("MainWindow", "Name"))
        self.StudentID.setToolTip(_translate("MainWindow", "Student ID"))
        self.StudentID.setPlaceholderText(_translate("MainWindow", "XXXX-XXXX"))
        self.Gender.setToolTip(_translate("MainWindow", "Gender"))
        self.YearLevel.setToolTip(_translate("MainWindow", "Student Year Level"))
        self.YearLevel.setPlaceholderText(_translate("MainWindow", "Year Level"))
        self.CouseCode.setToolTip(_translate("MainWindow", "Course Code"))
        self.label.setText(_translate("MainWindow", "ADD STUDENT"))
        self.SaveStudent.setToolTip(_translate("MainWindow", "Add Student"))
        self.SaveStudent.setText(_translate("MainWindow", "ADD"))
        self.label_2.setText(_translate("MainWindow", "ADD COURSE"))
        self.CourseCodeAdd.setToolTip(_translate("MainWindow", "Course Code"))
        self.CourseCodeAdd.setPlaceholderText(_translate("MainWindow", "Course Code"))
        self.SaveCourse.setToolTip(_translate("MainWindow", "Add Course"))
        self.SaveCourse.setText(_translate("MainWindow", "ADD"))
        self.CourseNameAdd.setToolTip(_translate("MainWindow", "Course Name"))
        self.CourseNameAdd.setPlaceholderText(_translate("MainWindow", "Course Name"))
        self.NameEdit.setToolTip(_translate("MainWindow", "Student Name"))
        self.NameEdit.setPlaceholderText(_translate("MainWindow", "Name"))
        self.YearLevelEdit.setToolTip(_translate("MainWindow", "Student Year Level"))
        self.YearLevelEdit.setPlaceholderText(_translate("MainWindow", "Year Level"))
        self.StudentIDEdit.setToolTip(_translate("MainWindow", "Student ID"))
        self.StudentIDEdit.setPlaceholderText(_translate("MainWindow", "XXXX-XXXX"))
        self.CouseCodeEdit.setToolTip(_translate("MainWindow", "Course Code"))
        self.GenderEdit.setToolTip(_translate("MainWindow", "Gender"))
        self.SaveStudentEdit.setToolTip(_translate("MainWindow", "Save Changes"))
        self.SaveStudentEdit.setText(_translate("MainWindow", "SAVE"))
        self.label_5.setText(_translate("MainWindow", "EDIT STUDENT"))
        self.label_6.setText(_translate("MainWindow", "EDIT COURSE"))
        self.CourseNameEdit.setToolTip(_translate("MainWindow", "Course Name"))
        self.CourseNameEdit.setPlaceholderText(_translate("MainWindow", "Course Name"))
        self.CourseCodeCourseEdit.setToolTip(_translate("MainWindow", "Course Code"))
        self.CourseCodeCourseEdit.setPlaceholderText(_translate("MainWindow", "Course Code"))
        self.SaveCourseEdit.setToolTip(_translate("MainWindow", "Save Changes"))
        self.SaveCourseEdit.setText(_translate("MainWindow", "SAVE"))
        self.label_7.setText(_translate("MainWindow", "DELETE MODE"))
        self.label_8.setText(_translate("MainWindow", "Click on the Student or Course"))
        self.label_9.setText(_translate("MainWindow", "That you wish to delete"))
        self.label_10.setText(_translate("MainWindow", "! WARNING !"))
        self.label_12.setText(_translate("MainWindow", " EDIT MODE"))
        self.label_13.setText(_translate("MainWindow", "Click on the Student or Course"))
        self.label_14.setText(_translate("MainWindow", "That you wish to Edit"))
        self.label_4.setText(_translate("MainWindow", "SSIS"))
        item = self.StudentTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Student ID"))
        item = self.StudentTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.StudentTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Year Level"))
        item = self.StudentTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.StudentTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Course Code"))
        item = self.CourseTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Course Code"))
        item = self.CourseTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Course Name"))
        self.SearchStudent.setToolTip(_translate("MainWindow", "Enter Student ID"))
        self.SearchStudent.setPlaceholderText(_translate("MainWindow", "XXXX-XXXX"))
        self.SearchCourse.setToolTip(_translate("MainWindow", "Enter Course Code"))
        self.SearchCourse.setPlaceholderText(_translate("MainWindow", "ex. BSCS"))
        self.SearchStudentB.setToolTip(_translate("MainWindow", "Search Student"))
        self.EditButton.setToolTip(_translate("MainWindow", "Edit Mode"))
        self.DeleteButton.setToolTip(_translate("MainWindow", "Delete Mode"))
        self.ViewButton.setToolTip(_translate("MainWindow", "View Mode"))
        self.SearchCourseB.setToolTip(_translate("MainWindow", "Search Course"))
        self.AddStudentB.setToolTip(_translate("MainWindow", "Add Student"))
        self.AddCourseB.setToolTip(_translate("MainWindow", "Add Course"))
#import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
